config:
  backup: true
  create: true
  dotpath: ./
dotfiles:
  d_bin:
    dst: ~/.bin
    src: bin
  d_ultisnips:
    dst: ~/.vim/UltiSnips
    src: vim/UltiSnips
  f_gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
profiles:
  lenny:
    dotfiles:
    - d_ultisnips
    - d_bin
    - f_gitconfig
