[tools]
python = "3.11"
toolr = "latest"
uv = 'latest'

[settings]
python.uv_venv_auto = true
python.uv_venv_create_args = ['--seed']
python.compile = false
experimental = true
idiomatic_version_file_enable_tools = ["python"]
