[[plugins]]
repo = 'ujihisa/neco-look'
on_ft = ['markdown']


[[plugins]]
repo = 'gu-fan/riv.vim'
on_ft = ['rst']

[[plugins]]
repo = 'ekalinin/Dockerfile.vim'
on_ft = ['Dockerfile']

[[plugins]]
repo = 'Glench/Vim-Jinja2-Syntax'

[[plugins]]
repo = 'saltstack/salt-vim'
on_ft = ['sls']
depends = ['Vim-Jinja2-Syntax']
