[[plugins]]
repo = 'Shougo/dein.vim'

#[[plugins]]
#repo = 'saltstack/salt-vim'

#[[plugins]]
#repo = 'tfnico/vim-gradle'

#[[plugins]]
#repo = 'elubow/cql-vim'

# colorscheme & syntax highlighting
#[[plugins]]
#repo = 'mhartington/oceanic-next'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

#[[plugins]]
#repo = 'frankier/neovim-colors-solarized-truecolor-only'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'Raimondi/delimitMate'

[[plugins]]
repo = 'valloric/MatchTagAlways'

#[[plugins]]
#repo = 'chr4/nginx.vim'

#[[plugins]]
#repo = 'mitsuhiko/fruity-vim-colorscheme'

[[plugins]]
repo = 'luochen1990/rainbow'

# Git helpers
#[[plugins]]
#repo = 'gregsexton/gitv'

[[plugins]]
repo = 'tpope/vim-fugitive'

#[[plugins]]
#repo = 'jreybert/vimagit'

[[plugins]]
repo = 'airblade/vim-gitgutter'

#[[plugins]]
#repo = 'Xuyuanp/nerdtree-git-plugin'

#[[plugins]]
#repo = 'jaxbot/github-issues.vim'

# utils
#[[plugins]]
#repo = 'benekastah/neomake'
#rev = 'e06f85e1651f5fe8841df3c85df1c51a891ccac4'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

#[[plugins]]
#repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'embear/vim-localvimrc'

#[[plugins]]
#repo = 'Rykka/clickable.vim'

[[plugins]]
repo = 'lambdalisue/vim-pyenv'

#[[plugins]]
#repo = 'janko-m/vim-test'

#[[plugins]]
#repo = 'kassio/neoterm'

[[plugins]]
repo = 'tmux-plugins/vim-tmux'

[[plugins]]
repo = 'edkolev/tmuxline.vim'

#[[plugins]]
#repo = 'milkypostman/vim-togglelist'

# Shougo
#[[plugins]]
#repo = 'Shougo/unite.vim'

#[[plugins]]
#repo = 'Shougo/unite-outline'

#[[plugins]]
#repo = 'ujihisa/unite-colorscheme'

[[plugins]]
repo = 'Shougo/denite.nvim'

#[[plugins]]
#repo = 'Shougo/vimfiler.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
# Required system-wide python-jedi or jedi intalled on virtualenv
repo = "maralla/completor.vim"

#[[plugins]]
#repo = 'Shougo/deoplete.nvim'

#[[plugins]]
#repo = 'zchee/deoplete-jedi'

#[[plugins]]
#repo = 'Shougo/neco-vim'

#[[plugins]]
#repo = 'Shougo/neoinclude.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

#[[plugins]]
#repo = 'Shougo/neosnippet.vim'

#[[plugins]]
#repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'honza/vim-snippets'
depends = ['ultisnips']

[[plugins]]
repo = 'sirver/ultisnips'

#[[plugins]]
#repo = 'mattn/gist-vim'
#depends = ['webapi-vim']

#[[plugins]]
#repo = 'mattn/webapi-vim'

#[[plugins]]
#repo = 'rhysd/github-complete.vim'

#[[plugins]]
#repo = 'junegunn/goyo.vim'

#[[plugins]]
#repo = 'junegunn/limelight.vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'svermeulen/vim-easyclip'
depends = ['tpope/vim-repeat']
