# Add ~/.local/bin/ to the PATH
typeset -U path PATH
GOPATH=~/.go
path=(~/.local/bin $GOPATH/bin /opt/homebrew/opt/mysql-client@8.4/bin $path)
export PATH
export GOPATH

export EDITOR=$(which nvim)

export CLICOLOR=1
